version: '3'

services:
  chopsticks:
    image: oven/bun:1
    container_name: chopsticks-node
    volumes:
      - ./:/home/bun/app
      # - ./.bunx-cache:/root/.bun/install/cache
    command: bunx @acala-network/chopsticks@latest -c ./configs/karura.yml
    ports:
      - 8000:8000

  postgres:
    image: postgres:12-alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres

  subquery-node:
    image: acala/evm-subql:latest
    volumes:
       - ./configs/subql/karura.yaml:/app/karura.yaml
       - ./configs/subql/acala.yaml:/app/acala.yaml
    ports:
      - 3000:3000
    depends_on:
      - chopsticks
      - postgres
    restart: always
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: host.docker.internal
      DB_PORT: 5432
    command:
      - -f=./karura.yaml
      - --network-endpoint=ws://chopsticks:8000
      - --db-schema=acala_evm
      - --log-level=info
      - --unsafe
      - --disable-historical

  graphql-engine:
    image: subquerynetwork/subql-query:v2.10.0
    container_name: graphql-engine
    ports:
      - 3001:3001
    depends_on:
      - subquery-node
    restart: always
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      PORT: 3001
    command:
      - --name=acala_evm
      - --playground
      - --indexer=http://subquery-node:3000

  eth-rpc-adapter:
    image: acala/eth-rpc-adapter:latest
    environment:
      - SUBQL_URL=http://graphql-engine:3001
      - ENDPOINT_URL=ws://chopsticks:8000
    command: yarn start
    ports:
      - 8545:8545
    restart: always
    depends_on:
      - chopsticks
    extra_hosts:
      - host.docker.internal:host-gateway
