compressionLevel: mixed

enableGlobalCache: false

httpProxy: "http://0.0.0.0:7890"

httpsProxy: "http://0.0.0.0:7890"

nodeLinker: node-modules

npmPublishAccess: public

npmPublishRegistry: "https://registry.npmjs.org/"

npmRegistryServer: "https://registry.npmjs.org/"

yarnPath: .yarn/releases/yarn-4.0.2.cjs
