coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
        base: auto
    patch:
      default:
        target: auto
        threshold: 0%
        base: auto

comment:
  layout: "reach, diff, flags, files"
  behavior: new
  require_changes: false
  require_base: false
  require_head: false
