/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface ILinkdropERC20Interface extends ethers.utils.Interface {
  functions: {
    "checkClaimParams(uint256,address,uint256,uint256,address,bytes,address,bytes,uint256)": FunctionFragment;
    "verifyLinkdropSignerSignature(uint256,address,uint256,uint256,address,bytes)": FunctionFragment;
    "verifyReceiverSignature(address,address,bytes)": FunctionFragment;
    "claim(uint256,address,uint256,uint256,address,bytes,address,bytes,address,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "checkClaimParams",
    values: [
      BigNumberish,
      string,
      BigNumberish,
      BigNumberish,
      string,
      BytesLike,
      string,
      BytesLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyLinkdropSignerSignature",
    values: [
      BigNumberish,
      string,
      BigNumberish,
      BigNumberish,
      string,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyReceiverSignature",
    values: [string, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claim",
    values: [
      BigNumberish,
      string,
      BigNumberish,
      BigNumberish,
      string,
      BytesLike,
      string,
      BytesLike,
      string,
      BigNumberish
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "checkClaimParams",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyLinkdropSignerSignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyReceiverSignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;

  events: {};
}

export class ILinkdropERC20 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: ILinkdropERC20Interface;

  functions: {
    checkClaimParams(
      _weiAmount: BigNumberish,
      _tokenAddress: string,
      _tokenAmount: BigNumberish,
      _expiration: BigNumberish,
      _linkId: string,
      _linkdropSignerSignature: BytesLike,
      _receiver: string,
      _receiverSignature: BytesLike,
      _fee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    verifyLinkdropSignerSignature(
      _weiAmount: BigNumberish,
      _tokenAddress: string,
      _tokenAmount: BigNumberish,
      _expiration: BigNumberish,
      _linkId: string,
      _signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    verifyReceiverSignature(
      _linkId: string,
      _receiver: string,
      _signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    claim(
      _weiAmount: BigNumberish,
      _tokenAddress: string,
      _tokenAmount: BigNumberish,
      _expiration: BigNumberish,
      _linkId: string,
      _linkdropSignerSignature: BytesLike,
      _receiver: string,
      _receiverSignature: BytesLike,
      _feeReceiver: string,
      _fee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  checkClaimParams(
    _weiAmount: BigNumberish,
    _tokenAddress: string,
    _tokenAmount: BigNumberish,
    _expiration: BigNumberish,
    _linkId: string,
    _linkdropSignerSignature: BytesLike,
    _receiver: string,
    _receiverSignature: BytesLike,
    _fee: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  verifyLinkdropSignerSignature(
    _weiAmount: BigNumberish,
    _tokenAddress: string,
    _tokenAmount: BigNumberish,
    _expiration: BigNumberish,
    _linkId: string,
    _signature: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  verifyReceiverSignature(
    _linkId: string,
    _receiver: string,
    _signature: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  claim(
    _weiAmount: BigNumberish,
    _tokenAddress: string,
    _tokenAmount: BigNumberish,
    _expiration: BigNumberish,
    _linkId: string,
    _linkdropSignerSignature: BytesLike,
    _receiver: string,
    _receiverSignature: BytesLike,
    _feeReceiver: string,
    _fee: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    checkClaimParams(
      _weiAmount: BigNumberish,
      _tokenAddress: string,
      _tokenAmount: BigNumberish,
      _expiration: BigNumberish,
      _linkId: string,
      _linkdropSignerSignature: BytesLike,
      _receiver: string,
      _receiverSignature: BytesLike,
      _fee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    verifyLinkdropSignerSignature(
      _weiAmount: BigNumberish,
      _tokenAddress: string,
      _tokenAmount: BigNumberish,
      _expiration: BigNumberish,
      _linkId: string,
      _signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    verifyReceiverSignature(
      _linkId: string,
      _receiver: string,
      _signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    claim(
      _weiAmount: BigNumberish,
      _tokenAddress: string,
      _tokenAmount: BigNumberish,
      _expiration: BigNumberish,
      _linkId: string,
      _linkdropSignerSignature: BytesLike,
      _receiver: string,
      _receiverSignature: BytesLike,
      _feeReceiver: string,
      _fee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    checkClaimParams(
      _weiAmount: BigNumberish,
      _tokenAddress: string,
      _tokenAmount: BigNumberish,
      _expiration: BigNumberish,
      _linkId: string,
      _linkdropSignerSignature: BytesLike,
      _receiver: string,
      _receiverSignature: BytesLike,
      _fee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    verifyLinkdropSignerSignature(
      _weiAmount: BigNumberish,
      _tokenAddress: string,
      _tokenAmount: BigNumberish,
      _expiration: BigNumberish,
      _linkId: string,
      _signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    verifyReceiverSignature(
      _linkId: string,
      _receiver: string,
      _signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    claim(
      _weiAmount: BigNumberish,
      _tokenAddress: string,
      _tokenAmount: BigNumberish,
      _expiration: BigNumberish,
      _linkId: string,
      _linkdropSignerSignature: BytesLike,
      _receiver: string,
      _receiverSignature: BytesLike,
      _feeReceiver: string,
      _fee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    checkClaimParams(
      _weiAmount: BigNumberish,
      _tokenAddress: string,
      _tokenAmount: BigNumberish,
      _expiration: BigNumberish,
      _linkId: string,
      _linkdropSignerSignature: BytesLike,
      _receiver: string,
      _receiverSignature: BytesLike,
      _fee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    verifyLinkdropSignerSignature(
      _weiAmount: BigNumberish,
      _tokenAddress: string,
      _tokenAmount: BigNumberish,
      _expiration: BigNumberish,
      _linkId: string,
      _signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    verifyReceiverSignature(
      _linkId: string,
      _receiver: string,
      _signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    claim(
      _weiAmount: BigNumberish,
      _tokenAddress: string,
      _tokenAmount: BigNumberish,
      _expiration: BigNumberish,
      _linkId: string,
      _linkdropSignerSignature: BytesLike,
      _receiver: string,
      _receiverSignature: BytesLike,
      _feeReceiver: string,
      _fee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
