/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface ILinkdropFactoryERC721Interface extends ethers.utils.Interface {
  functions: {
    "claimERC721(uint256,address,uint256,uint256,address,address,uint256,bytes,address,bytes)": FunctionFragment;
    "checkClaimParamsERC721(uint256,address,uint256,uint256,address,address,uint256,bytes,address,bytes)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "claimERC721",
    values: [
      BigNumberish,
      string,
      BigNumberish,
      BigNumberish,
      string,
      string,
      BigNumberish,
      BytesLike,
      string,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "checkClaimParamsERC721",
    values: [
      BigNumberish,
      string,
      BigNumberish,
      BigNumberish,
      string,
      string,
      BigNumberish,
      BytesLike,
      string,
      BytesLike
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "claimERC721",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkClaimParamsERC721",
    data: BytesLike
  ): Result;

  events: {};
}

export class ILinkdropFactoryERC721 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: ILinkdropFactoryERC721Interface;

  functions: {
    claimERC721(
      _weiAmount: BigNumberish,
      _nftAddress: string,
      _tokenId: BigNumberish,
      _expiration: BigNumberish,
      _linkId: string,
      _linkdropMaster: string,
      _campaignId: BigNumberish,
      _linkdropSignerSignature: BytesLike,
      _receiver: string,
      _receiverSignature: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    checkClaimParamsERC721(
      _weiAmount: BigNumberish,
      _nftAddress: string,
      _tokenId: BigNumberish,
      _expiration: BigNumberish,
      _linkId: string,
      _linkdropMaster: string,
      _campaignId: BigNumberish,
      _linkdropSignerSignature: BytesLike,
      _receiver: string,
      _receiverSignature: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  claimERC721(
    _weiAmount: BigNumberish,
    _nftAddress: string,
    _tokenId: BigNumberish,
    _expiration: BigNumberish,
    _linkId: string,
    _linkdropMaster: string,
    _campaignId: BigNumberish,
    _linkdropSignerSignature: BytesLike,
    _receiver: string,
    _receiverSignature: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  checkClaimParamsERC721(
    _weiAmount: BigNumberish,
    _nftAddress: string,
    _tokenId: BigNumberish,
    _expiration: BigNumberish,
    _linkId: string,
    _linkdropMaster: string,
    _campaignId: BigNumberish,
    _linkdropSignerSignature: BytesLike,
    _receiver: string,
    _receiverSignature: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    claimERC721(
      _weiAmount: BigNumberish,
      _nftAddress: string,
      _tokenId: BigNumberish,
      _expiration: BigNumberish,
      _linkId: string,
      _linkdropMaster: string,
      _campaignId: BigNumberish,
      _linkdropSignerSignature: BytesLike,
      _receiver: string,
      _receiverSignature: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    checkClaimParamsERC721(
      _weiAmount: BigNumberish,
      _nftAddress: string,
      _tokenId: BigNumberish,
      _expiration: BigNumberish,
      _linkId: string,
      _linkdropMaster: string,
      _campaignId: BigNumberish,
      _linkdropSignerSignature: BytesLike,
      _receiver: string,
      _receiverSignature: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    claimERC721(
      _weiAmount: BigNumberish,
      _nftAddress: string,
      _tokenId: BigNumberish,
      _expiration: BigNumberish,
      _linkId: string,
      _linkdropMaster: string,
      _campaignId: BigNumberish,
      _linkdropSignerSignature: BytesLike,
      _receiver: string,
      _receiverSignature: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    checkClaimParamsERC721(
      _weiAmount: BigNumberish,
      _nftAddress: string,
      _tokenId: BigNumberish,
      _expiration: BigNumberish,
      _linkId: string,
      _linkdropMaster: string,
      _campaignId: BigNumberish,
      _linkdropSignerSignature: BytesLike,
      _receiver: string,
      _receiverSignature: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    claimERC721(
      _weiAmount: BigNumberish,
      _nftAddress: string,
      _tokenId: BigNumberish,
      _expiration: BigNumberish,
      _linkId: string,
      _linkdropMaster: string,
      _campaignId: BigNumberish,
      _linkdropSignerSignature: BytesLike,
      _receiver: string,
      _receiverSignature: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    checkClaimParamsERC721(
      _weiAmount: BigNumberish,
      _nftAddress: string,
      _tokenId: BigNumberish,
      _expiration: BigNumberish,
      _linkId: string,
      _linkdropMaster: string,
      _campaignId: BigNumberish,
      _linkdropSignerSignature: BytesLike,
      _receiver: string,
      _receiverSignature: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
