/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface LinkdropStorageInterface extends ethers.utils.Interface {
  functions: {
    "claimedTo(address)": FunctionFragment;
    "initialized()": FunctionFragment;
    "version()": FunctionFragment;
    "owner()": FunctionFragment;
    "chainId()": FunctionFragment;
    "linkdropMaster()": FunctionFragment;
    "isLinkdropSigner(address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "claimedTo", values: [string]): string;
  encodeFunctionData(
    functionFragment: "initialized",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "version", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "chainId", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "linkdropMaster",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isLinkdropSigner",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "claimedTo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initialized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "version", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "chainId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "linkdropMaster",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isLinkdropSigner",
    data: BytesLike
  ): Result;

  events: {
    "Canceled(address)": EventFragment;
    "Claimed(address,uint256,address,uint256,address)": EventFragment;
    "ClaimedERC721(address,uint256,address,uint256,address)": EventFragment;
    "Paused()": EventFragment;
    "Unpaused()": EventFragment;
    "AddedSigningKey(address)": EventFragment;
    "RemovedSigningKey(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Canceled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Claimed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ClaimedERC721"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Paused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Unpaused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AddedSigningKey"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RemovedSigningKey"): EventFragment;
}

export type CanceledEvent = TypedEvent<[string] & { linkId: string }>;

export type ClaimedEvent = TypedEvent<
  [string, BigNumber, string, BigNumber, string] & {
    linkId: string;
    ethAmount: BigNumber;
    token: string;
    tokenAmount: BigNumber;
    receiver: string;
  }
>;

export type ClaimedERC721Event = TypedEvent<
  [string, BigNumber, string, BigNumber, string] & {
    linkId: string;
    ethAmount: BigNumber;
    nft: string;
    tokenId: BigNumber;
    receiver: string;
  }
>;

export type PausedEvent = TypedEvent<[] & {}>;

export type UnpausedEvent = TypedEvent<[] & {}>;

export type AddedSigningKeyEvent = TypedEvent<
  [string] & { linkdropSigner: string }
>;

export type RemovedSigningKeyEvent = TypedEvent<
  [string] & { linkdropSigner: string }
>;

export class LinkdropStorage extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: LinkdropStorageInterface;

  functions: {
    claimedTo(arg0: string, overrides?: CallOverrides): Promise<[string]>;

    initialized(overrides?: CallOverrides): Promise<[boolean]>;

    version(overrides?: CallOverrides): Promise<[BigNumber]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    chainId(overrides?: CallOverrides): Promise<[BigNumber]>;

    linkdropMaster(overrides?: CallOverrides): Promise<[string]>;

    isLinkdropSigner(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  claimedTo(arg0: string, overrides?: CallOverrides): Promise<string>;

  initialized(overrides?: CallOverrides): Promise<boolean>;

  version(overrides?: CallOverrides): Promise<BigNumber>;

  owner(overrides?: CallOverrides): Promise<string>;

  chainId(overrides?: CallOverrides): Promise<BigNumber>;

  linkdropMaster(overrides?: CallOverrides): Promise<string>;

  isLinkdropSigner(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  callStatic: {
    claimedTo(arg0: string, overrides?: CallOverrides): Promise<string>;

    initialized(overrides?: CallOverrides): Promise<boolean>;

    version(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<string>;

    chainId(overrides?: CallOverrides): Promise<BigNumber>;

    linkdropMaster(overrides?: CallOverrides): Promise<string>;

    isLinkdropSigner(arg0: string, overrides?: CallOverrides): Promise<boolean>;
  };

  filters: {
    "Canceled(address)"(
      linkId?: null
    ): TypedEventFilter<[string], { linkId: string }>;

    Canceled(linkId?: null): TypedEventFilter<[string], { linkId: string }>;

    "Claimed(address,uint256,address,uint256,address)"(
      linkId?: string | null,
      ethAmount?: null,
      token?: string | null,
      tokenAmount?: null,
      receiver?: null
    ): TypedEventFilter<
      [string, BigNumber, string, BigNumber, string],
      {
        linkId: string;
        ethAmount: BigNumber;
        token: string;
        tokenAmount: BigNumber;
        receiver: string;
      }
    >;

    Claimed(
      linkId?: string | null,
      ethAmount?: null,
      token?: string | null,
      tokenAmount?: null,
      receiver?: null
    ): TypedEventFilter<
      [string, BigNumber, string, BigNumber, string],
      {
        linkId: string;
        ethAmount: BigNumber;
        token: string;
        tokenAmount: BigNumber;
        receiver: string;
      }
    >;

    "ClaimedERC721(address,uint256,address,uint256,address)"(
      linkId?: string | null,
      ethAmount?: null,
      nft?: string | null,
      tokenId?: null,
      receiver?: null
    ): TypedEventFilter<
      [string, BigNumber, string, BigNumber, string],
      {
        linkId: string;
        ethAmount: BigNumber;
        nft: string;
        tokenId: BigNumber;
        receiver: string;
      }
    >;

    ClaimedERC721(
      linkId?: string | null,
      ethAmount?: null,
      nft?: string | null,
      tokenId?: null,
      receiver?: null
    ): TypedEventFilter<
      [string, BigNumber, string, BigNumber, string],
      {
        linkId: string;
        ethAmount: BigNumber;
        nft: string;
        tokenId: BigNumber;
        receiver: string;
      }
    >;

    "Paused()"(): TypedEventFilter<[], {}>;

    Paused(): TypedEventFilter<[], {}>;

    "Unpaused()"(): TypedEventFilter<[], {}>;

    Unpaused(): TypedEventFilter<[], {}>;

    "AddedSigningKey(address)"(
      linkdropSigner?: null
    ): TypedEventFilter<[string], { linkdropSigner: string }>;

    AddedSigningKey(
      linkdropSigner?: null
    ): TypedEventFilter<[string], { linkdropSigner: string }>;

    "RemovedSigningKey(address)"(
      linkdropSigner?: null
    ): TypedEventFilter<[string], { linkdropSigner: string }>;

    RemovedSigningKey(
      linkdropSigner?: null
    ): TypedEventFilter<[string], { linkdropSigner: string }>;
  };

  estimateGas: {
    claimedTo(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    initialized(overrides?: CallOverrides): Promise<BigNumber>;

    version(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    chainId(overrides?: CallOverrides): Promise<BigNumber>;

    linkdropMaster(overrides?: CallOverrides): Promise<BigNumber>;

    isLinkdropSigner(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    claimedTo(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialized(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    version(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    chainId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    linkdropMaster(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isLinkdropSigner(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
