specVersion: 1.0.0
name: '@acala-network/evm-subql'
version: 1.0.0
runner:
  node:
    name: '@subql/node'
    version: 1.21.2
  query:
    name: '@subql/query'
    version: 1.4.0
description: 'subquery for Acala EVM+'
repository: 'https://github.com/AcalaNetwork/bodhi.js/tree/master/evm-subql'
schema:
  file: ./schema.graphql
network:
  # Acala
  chainId: '0xfc41b9bd8ef8fe53d58c7ea67c794c7ec9a73daf05e6d54b14ff6342c99ba64c'
  endpoint: ws://chopsticks:8000
  chaintypes:
    file: ./dist/chain-types/index.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 5108461
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
