specVersion: 1.0.0
name: '@acala-network/evm-subql'
version: 1.0.0
runner:
  node:
    name: '@subql/node'
    version: 1.21.2
  query:
    name: '@subql/query'
    version: 1.4.0
description: 'subquery for Karura EVM+'
repository: 'https://github.com/AcalaNetwork/bodhi.js/tree/master/evm-subql'
schema:
  file: ./schema.graphql
network:
  # Karura
  chainId: '0xbaf5aabe40646d11f0ee8abbdc64f4a4b7674925cba08e4a05ff9ebed6e2126b'
  endpoint: ws://chopsticks:8000
  chaintypes:
    file: ./dist/chain-types/index.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 5853808
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
