version: '3'

services:
  mandala-node:
    image: ghcr.io/acalanetwork/mandala-node:sha-e894cf6
    ports:
      - 9944:9944
    command:
      - --dev
      - -lruntime=debug
      - -levm=debug
      - --ws-port=9944
      - --ws-external
      - --rpc-port=9933
      - --rpc-external
      - --rpc-cors=all
      - --rpc-methods=unsafe
      - --instant-sealing
      - --tmp

  postgres:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

  subquery-node:
    image: onfinality/subql-node:v1.7.0
    depends_on:
      - postgres
      - mandala-node
    ports:
      - 3000:3000
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    volumes:
      - ./:/app
    command:
      - -f=/app
      - --network-endpoint=ws://mandala-node:9944
      - --db-schema=acala_evm
      - --log-level=debug
      - --unsafe

  graphql-engine:
    image: onfinality/subql-query:v1.4.0
    ports:
      - 3001:3001
    depends_on:
      - postgres
      - subquery-node
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      PORT: 3001
    command:
      - --name=acala_evm
      - --playground
      - --indexer=http://subquery-node:3000

volumes:
  postgres:
