version: '3'

services:
  mandala-node:
    image: acala/mandala-node:dc8d634b
    ports:
      - 9944:9944
    command:
      - --dev
      - -lruntime=debug
      - -levm=debug
      - --ws-port=9944
      - --ws-external=true
      - --rpc-port=9933
      - --rpc-external=true
      - --rpc-cors=all
      - --rpc-methods=unsafe
      - --tmp

  postgres:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

  subquery-node:
    image: onfinality/subql-node:latest
    depends_on:
      - 'postgres'
    restart: always
    network_mode: host
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: localhost
      DB_PORT: 5432
    volumes:
      - ./:/app
    command:
      - -f=/app
      - --local
      - --subquery-name=acala-evm
      - --local
      - --log-level=debug

  graphql-engine:
    image: onfinality/subql-query:latest
    ports:
      - 3001:3001
    depends_on:
      - 'postgres'
      - 'subquery-node'
    restart: always
    network_mode: host
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: localhost
      DB_PORT: 5432
      PORT: 3001
    command:
      - --name=acala-evm
      - --playground
      - --indexer=http://localhost:3000

volumes:
  postgres:
