version: '3'

services:
  postgres:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    volumes:
      - .data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

  subquery-node:
    image: onfinality/subql-node:latest
    ports:
      - 3000:3000
    depends_on:
      - 'postgres'
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    volumes:
      - ./:/app
    command:
      - -f=/app
      - --network-endpoint=ws://host.docker.internal:9944
      - --subquery-name=acala-evm
      - --log-level=debug

  graphql-engine:
    image: onfinality/subql-query:latest
    ports:
      - 3001:3001
    depends_on:
      - 'postgres'
      - 'subquery-node'
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      PORT: 3001
    command:
      - --name=acala-evm
      - --playground
      - --indexer=http://subquery-node:3000

volumes:
  postgres:
