specVersion: 1.0.0
name: '@acala-network/evm-subql'
version: 1.0.0
runner:
  node:
    name: '@subql/node'
    version: 0.33.0
  query:
    name: '@subql/query'
    version: 0.14.1
description: 'subquery for Acala EVM+'
repository: 'https://github.com/AcalaNetwork/bodhi.js/tree/master/evm-subql'
schema:
  file: ./schema.graphql
network:
  # karura
  # chainId: '0xbaf5aabe40646d11f0ee8abbdc64f4a4b7674925cba08e4a05ff9ebed6e2126b'

  # mandala
  chainId: '0x42375bbff13887e1967c7a1836b7b9c123500ad14705d7cd9f21cedba90c6a3a'
  endpoint: ws://localhost:9944
  chaintypes:
    # TODO: can generate this dynamically with `yarn build` using `@acala-network/types`
    file: ./types.json
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleEvmEvent
          kind: substrate/EventHandler
          filter:
            module: evm
