specVersion: 0.2.0
name: Acala EVM Subql
version: 0.0.1
description: ''
repository: ''
schema:
  file: ./schema.graphql
network:
  genesisHash: '0x5c562e6300954998233c9a40b6b86f3028977e6d32d0da1af207738d19f98c1b'
  endpoint: >-
    wss://node-6870830370282213376.rz.onfinality.io/ws?apikey=0f273197-e4d5-45e2-b23e-03b015cb7000
  chaintypes:
    file: ./types.json
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleEvmEvent
          kind: substrate/EventHandler
          filter:
            module: evm
