version: '3'

services:
  mandala-node:
    image: ghcr.io/acalanetwork/mandala-node:sha-4c127a1
    ports:
      - 9944:9944
    command:
      - --dev
      - -lruntime=debug
      - -levm=debug
      - --ws-port=9944
      - --ws-external
      - --rpc-port=9933
      - --rpc-external
      - --rpc-cors=all
      - --rpc-methods=unsafe
      - --pruning=archive
      - --keep-blocks=archive
      - --instant-sealing
      - --tmp

  eth-rpc-adaptor:
    image: acala/eth-rpc-adapter:7e4b68b
    ports:
      - 8545:8545
    depends_on:
      - mandala-node
    restart: always
    environment:
      ENDPOINT_URL: ws://mandala-node:9944
      LOCAL_MODE: 1
