/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ILinkdropERC20,
  ILinkdropERC20Interface,
} from "../ILinkdropERC20";

const _abi = [
  {
    constant: true,
    inputs: [
      {
        name: "_weiAmount",
        type: "uint256",
      },
      {
        name: "_tokenAddress",
        type: "address",
      },
      {
        name: "_tokenAmount",
        type: "uint256",
      },
      {
        name: "_expiration",
        type: "uint256",
      },
      {
        name: "_linkId",
        type: "address",
      },
      {
        name: "_linkdropSignerSignature",
        type: "bytes",
      },
      {
        name: "_receiver",
        type: "address",
      },
      {
        name: "_receiverSignature",
        type: "bytes",
      },
      {
        name: "_fee",
        type: "uint256",
      },
    ],
    name: "checkClaimParams",
    outputs: [
      {
        name: "",
        type: "bool",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      {
        name: "_weiAmount",
        type: "uint256",
      },
      {
        name: "_tokenAddress",
        type: "address",
      },
      {
        name: "_tokenAmount",
        type: "uint256",
      },
      {
        name: "_expiration",
        type: "uint256",
      },
      {
        name: "_linkId",
        type: "address",
      },
      {
        name: "_signature",
        type: "bytes",
      },
    ],
    name: "verifyLinkdropSignerSignature",
    outputs: [
      {
        name: "",
        type: "bool",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      {
        name: "_linkId",
        type: "address",
      },
      {
        name: "_receiver",
        type: "address",
      },
      {
        name: "_signature",
        type: "bytes",
      },
    ],
    name: "verifyReceiverSignature",
    outputs: [
      {
        name: "",
        type: "bool",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        name: "_weiAmount",
        type: "uint256",
      },
      {
        name: "_tokenAddress",
        type: "address",
      },
      {
        name: "_tokenAmount",
        type: "uint256",
      },
      {
        name: "_expiration",
        type: "uint256",
      },
      {
        name: "_linkId",
        type: "address",
      },
      {
        name: "_linkdropSignerSignature",
        type: "bytes",
      },
      {
        name: "_receiver",
        type: "address",
      },
      {
        name: "_receiverSignature",
        type: "bytes",
      },
      {
        name: "_feeReceiver",
        type: "address",
      },
      {
        name: "_fee",
        type: "uint256",
      },
    ],
    name: "claim",
    outputs: [
      {
        name: "",
        type: "bool",
      },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ILinkdropERC20__factory {
  static readonly abi = _abi;
  static createInterface(): ILinkdropERC20Interface {
    return new utils.Interface(_abi) as ILinkdropERC20Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ILinkdropERC20 {
    return new Contract(address, _abi, signerOrProvider) as ILinkdropERC20;
  }
}
