/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ILinkdropFactoryERC20,
  ILinkdropFactoryERC20Interface,
} from "../ILinkdropFactoryERC20";

const _abi = [
  {
    constant: true,
    inputs: [
      {
        name: "_weiAmount",
        type: "uint256",
      },
      {
        name: "_tokenAddress",
        type: "address",
      },
      {
        name: "_tokenAmount",
        type: "uint256",
      },
      {
        name: "_expiration",
        type: "uint256",
      },
      {
        name: "_linkId",
        type: "address",
      },
      {
        name: "_linkdropMaster",
        type: "address",
      },
      {
        name: "_campaignId",
        type: "uint256",
      },
      {
        name: "_linkdropSignerSignature",
        type: "bytes",
      },
      {
        name: "_receiver",
        type: "address",
      },
      {
        name: "_receiverSignature",
        type: "bytes",
      },
    ],
    name: "checkClaimParams",
    outputs: [
      {
        name: "",
        type: "bool",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        name: "_weiAmount",
        type: "uint256",
      },
      {
        name: "_tokenAddress",
        type: "address",
      },
      {
        name: "_tokenAmount",
        type: "uint256",
      },
      {
        name: "_expiration",
        type: "uint256",
      },
      {
        name: "_linkId",
        type: "address",
      },
      {
        name: "_linkdropMaster",
        type: "address",
      },
      {
        name: "_campaignId",
        type: "uint256",
      },
      {
        name: "_linkdropSignerSignature",
        type: "bytes",
      },
      {
        name: "_receiver",
        type: "address",
      },
      {
        name: "_receiverSignature",
        type: "bytes",
      },
    ],
    name: "claim",
    outputs: [
      {
        name: "",
        type: "bool",
      },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ILinkdropFactoryERC20__factory {
  static readonly abi = _abi;
  static createInterface(): ILinkdropFactoryERC20Interface {
    return new utils.Interface(_abi) as ILinkdropFactoryERC20Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ILinkdropFactoryERC20 {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ILinkdropFactoryERC20;
  }
}
