/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ILinkdropFactoryERC721,
  ILinkdropFactoryERC721Interface,
} from "../ILinkdropFactoryERC721";

const _abi = [
  {
    constant: false,
    inputs: [
      {
        name: "_weiAmount",
        type: "uint256",
      },
      {
        name: "_nftAddress",
        type: "address",
      },
      {
        name: "_tokenId",
        type: "uint256",
      },
      {
        name: "_expiration",
        type: "uint256",
      },
      {
        name: "_linkId",
        type: "address",
      },
      {
        name: "_linkdropMaster",
        type: "address",
      },
      {
        name: "_campaignId",
        type: "uint256",
      },
      {
        name: "_linkdropSignerSignature",
        type: "bytes",
      },
      {
        name: "_receiver",
        type: "address",
      },
      {
        name: "_receiverSignature",
        type: "bytes",
      },
    ],
    name: "claimERC721",
    outputs: [
      {
        name: "",
        type: "bool",
      },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      {
        name: "_weiAmount",
        type: "uint256",
      },
      {
        name: "_nftAddress",
        type: "address",
      },
      {
        name: "_tokenId",
        type: "uint256",
      },
      {
        name: "_expiration",
        type: "uint256",
      },
      {
        name: "_linkId",
        type: "address",
      },
      {
        name: "_linkdropMaster",
        type: "address",
      },
      {
        name: "_campaignId",
        type: "uint256",
      },
      {
        name: "_linkdropSignerSignature",
        type: "bytes",
      },
      {
        name: "_receiver",
        type: "address",
      },
      {
        name: "_receiverSignature",
        type: "bytes",
      },
    ],
    name: "checkClaimParamsERC721",
    outputs: [
      {
        name: "",
        type: "bool",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
];

export class ILinkdropFactoryERC721__factory {
  static readonly abi = _abi;
  static createInterface(): ILinkdropFactoryERC721Interface {
    return new utils.Interface(_abi) as ILinkdropFactoryERC721Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ILinkdropFactoryERC721 {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ILinkdropFactoryERC721;
  }
}
