version: '3.9'

services:
  mandala-node:
    image: ghcr.io/acalanetwork/mandala-node:sha-a32c40b
    ports:
      - 9933:9933
      - 9944:9944
    healthcheck:
      test: "curl --fail -X POST -H \"Content-Type: application/json\" http://localhost:9933 -d \"{\"jsonrpc\": \"2.0\" }\" || exit 1"
      interval: 10s
      retries: 10
      start_period: 30s
    command:
      - --dev
      - -lruntime=debug
      - -levm=debug
      - --ws-port=9944
      - --ws-external
      - --rpc-port=9933
      - --rpc-external
      - --rpc-cors=all
      - --rpc-methods=unsafe
      - --pruning=archive
      - --instant-sealing
      - --tmp

  postgres:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

  subquery-node:
    image: onfinality/subql-node:v1.21.2
    depends_on:
      postgres: 
        condition: service_started
      mandala-node:
        condition: service_healthy
    ports:
      - 3000:3000
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    volumes:
      - ./:/app
    command:
      - -f=/app
      - --network-endpoint=ws://mandala-node:9944
      - --db-schema=acala_evm
      - --log-level=debug
      - --unsafe
      - --disable-historical

  graphql-engine:
    image: onfinality/subql-query:v1.4.0
    ports:
      - 3001:3001
    depends_on:
      - postgres
      - subquery-node
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      PORT: 3001
    command:
      - --name=acala_evm
      - --playground
      - --indexer=http://subquery-node:3000

volumes:
  postgres:
