specVersion: 1.0.0
name: '@acala-network/evm-subql'
version: 1.0.0
runner:
  node:
    name: '@subql/node'
    version: 1.21.2
  query:
    name: '@subql/query'
    version: 1.4.0
description: 'subquery for Local Mandala EVM+'
repository: 'https://github.com/AcalaNetwork/bodhi.js/tree/master/evm-subql'
schema:
  file: ./schema.graphql
network:
  # local mandala
  chainId: '0x6b4acf5a0264399326a45d79037b1fcd4c4f3259589bd7642f1272b6adf0e00d'
  endpoint: ws://localhost:9944
  chaintypes:
    # TODO: can generate this dynamically with `yarn build` using `@acala-network/types`
    file: ./dist/chain-types/index.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
