specVersion: 1.0.0
name: '@acala-network/evm-subql'
version: 1.0.0
runner:
  node:
    name: '@subql/node'
    version: 1.21.2
  query:
    name: '@subql/query'
    version: 1.4.0
description: 'subquery for Local Mandala EVM+'
repository: 'https://github.com/AcalaNetwork/bodhi.js/tree/master/evm-subql'
schema:
  file: ./schema.graphql
network:
  # local mandala
  chainId: '0xa547d06d0a044a5e3c319941fd033a88f2d3e8e1eab2c2f0f7c3d8b8dac23d6c'
  endpoint: ws://localhost:9944
  chaintypes:
    # TODO: can generate this dynamically with `yarn build` using `@acala-network/types`
    file: ./dist/chain-types/index.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
