endpoint: wss://acala-rpc.aca-api.network
mock-signature-host: true
# block: 2694000
db: ./db.sqlite
wasm-override: ./wasm/acala-2220.wasm

import-storage:
  Sudo:
    Key: 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY # Alice
  System:
    Account:
    - - - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
      - providers: 1
        data:
          free: 1000000000000000
  EvmAccounts:
    EvmAddresses:
    - - - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
      - '0x75E480dB528101a381Ce68544611C169Ad7EB342'
    Accounts:
    - - - '0x75E480dB528101a381Ce68544611C169Ad7EB342'
      - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
