name: Publish
on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: git config email
        run: git config --local user.email bodhibot@users.noreply.github.com

      - name: git config name
        run: git config --local user.name Bodhibot

      - name: setup node env
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'

      - name: install dependencies
        run: yarn install --immutable

      - name: build packages
        run: yarn build

      # Writes token to .yarnrc.yml. If written directly in .yarnrc.yml, it will cause an error
      - run: |
          echo npmAuthToken: "\${NPM_AUTH_TOKEN}" >> ./.yarnrc.yml

      - name: publish @acala-network/eth-transactions
        run: |
          TAG=$(node -p -e "require('./packages/eth-transactions/package.json').version.includes('-') ? '--tag beta' : ''")
          yarn workspace @acala-network/eth-transactions npm publish --tolerate-republish --access public $TAG
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: publish @acala-network/eth-providers
        run: |
          TAG=$(node -p -e "require('./packages/eth-providers/package.json').version.includes('-') ? '--tag beta' : ''")
          yarn workspace @acala-network/eth-providers npm publish --tolerate-republish --access public $TAG
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: publish @acala-network/eth-rpc-adapter
        run: |
          TAG=$(node -p -e "require('./packages/eth-rpc-adapter/package.json').version.includes('-') ? '--tag beta' : ''")
          yarn workspace @acala-network/eth-rpc-adapter npm publish --tolerate-republish --access public $TAG
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: publish @acala-network/bodhi
        run: |
          TAG=$(node -p -e "require('./packages/bodhi/package.json').version.includes('-') ? '--tag beta' : ''")
          yarn workspace @acala-network/bodhi npm publish --tolerate-republish --access public $TAG
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - run: |
          git checkout ./.yarnrc.yml
