name: Publish
on:
  push:
    tags:
      - v*

jobs:
  publish:
    name: 'Publish To NPM'
    if: github.event.base_ref=='refs/heads/master' # only trigger on master
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: git config email
        run: git config --local user.email bodhibot@users.noreply.github.com

      - name: git config name
        run: git config --local user.name Bodhibot

      - name: setup node env
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'

      - name: install dependencies
        run: node common/scripts/install-run-rush.js install

      - name: build packages
        run: node common/scripts/install-run-rush.js build --verbose --to @acala-network/bodhi

      - name: publish
        run: node common/scripts/install-run-rush.js publish --apply --publish --include-all --target-branch master --add-commit-details --set-access-level public -n ${{ secrets.NPM_AUTH_TOKEN }}
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

  tagged-release:
    name: 'Tagged Release'
    if: github.event.base_ref=='refs/heads/master' # only trigger on master
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          prerelease: false
