name: Build + E2E Tests
on: push

jobs:
  waffle-examples:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: test
        run: docker-compose up --abort-on-container-exit --exit-code-from=waffle-examples-test -- waffle-examples-test

  eth-providers:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: test
        run: docker-compose up --abort-on-container-exit --exit-code-from=eth-providers-test -- eth-providers-test

  eth-rpc-adaptor:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: test
        run: docker-compose up --abort-on-container-exit --exit-code-from=eth-rpc-adapter-test -- eth-rpc-adapter-test

  hardhat-examples:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: test
        run: docker-compose up --abort-on-container-exit --exit-code-from=hardhat-examples-test -- hardhat-examples-test

  truffle-examples:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: test
        run: docker-compose up --abort-on-container-exit --exit-code-from=truffle-examples-test -- truffle-examples-test
