name: Test All Packages
on: push

jobs:
  test-waffle:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Build the stack
        run: docker-compose build
      - name: Test
        run: docker-compose up
