name: Build + E2E Tests
on: push

jobs:
  clean-up-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        # Only cancel non-master branch runs
        if: ${{ github.ref != 'refs/heads/master' }}
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}

  waffle-examples:
    runs-on: [self-hosted, linux]
    needs: clean-up-actions
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: clean docker volume
        run: docker compose down -v postgres
      - name: test
        run: docker-compose up --abort-on-container-exit --exit-code-from=waffle-examples-test -- waffle-examples-test

  eth-providers:
    runs-on: [self-hosted, linux]
    needs: clean-up-actions
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: clean docker volume
        run: docker compose down -v postgres
      - name: test
        run: docker-compose up --abort-on-container-exit --exit-code-from=eth-providers-test --build -- eth-providers-test

  eth-rpc-adaptor:
    runs-on: [self-hosted, linux]
    needs: clean-up-actions
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: clean docker volume
        run: docker compose down -v postgres
      - name: test
        run: docker-compose up --abort-on-container-exit --exit-code-from=eth-rpc-adapter-test --build -- eth-rpc-adapter-test

  hardhat-examples:
    runs-on: [self-hosted, linux]
    needs: clean-up-actions
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: clean docker volume
        run: docker compose down -v postgres
      - name: test
        run: docker-compose up --abort-on-container-exit --exit-code-from=hardhat-examples-test --build -- hardhat-examples-test

  truffle-examples:
    runs-on: [self-hosted, linux]
    needs: clean-up-actions
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: clean docker volume
        run: docker compose down -v postgres
      - name: test
        run: docker-compose up --abort-on-container-exit --exit-code-from=truffle-examples-test --build -- truffle-examples-test
