name: Test All Packages
on: push

jobs:
  # test-waffle-examples:
  #   runs-on: [self-hosted, linux]
  #   steps:
  #     - name: checkout
  #       uses: actions/checkout@v2

  #     # - name: Build the stack
  #     #   run: docker-compose build
  #     - name: test
  #       run: docker-compose up --abort-on-container-exit --exit-code-from=test-waffle-examples -- test-waffle-examples

  # test-eth-providers:
  #   runs-on: [self-hosted, linux]
  #   steps:
  #     - name: checkout
  #       uses: actions/checkout@v2

  #     # - name: Build the stack
  #     #   run: docker-compose build
  #     - name: test
  #       run: docker-compose up --abort-on-container-exit --exit-code-from=test-eth-providers -- test-eth-providers

  test-all:
    runs-on: [self-hosted, linux]
    steps:
      - name: checkout
        uses: actions/checkout@v2

      # - name: Build the stack
      #   run: docker-compose build
      - name: test
        run: docker-compose up
