name: Tests
on:
  push:
    paths-ignore:
      - '**/README.md'

jobs:
  pkg-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project: [
          bodhi,
          eth-providers,
          eth-rpc-adapter,
          eth-transactions,
        ]
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: setup yarn
        run: npm install -g yarn

      - name: install deps
        run: yarn install --immutable

      - name: start test infra
        run: docker compose up -d

      - name: run tests
        run: yarn workspace @acala-network/${{ matrix.project }} run test:coverage

      - name: save coverage reports
        uses: actions/upload-artifact@v3
        with:
          name: coverage-${{ matrix.project }}
          path: packages/${{ matrix.project }}/coverage
          if-no-files-found: error
          include-hidden-files: true

      - name: dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2

  e2e-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project: [
          e2e-hardhat,
          e2e-truffle,
          e2e-viem,
        ]
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: setup yarn
        run: npm install -g yarn

      - name: install deps
        run: yarn install --immutable

      - name: start test infra
        run: docker compose up -d

      - name: start coverage server
        env:
          COVERAGE_DIR: eth-rpc-adapter/coverage-${{ matrix.project }}
        run: yarn workspace @acala-network/eth-rpc-adapter run start:coverage

      - name: install deps for e2e tests
        run: cd e2e-tests/${{ matrix.project }} && yarn install --immutable

      - name: run e2e tests
        run: cd e2e-tests/${{ matrix.project }} && yarn test:acalaFork

      - name: stop coverage server and generate coverage report
        run: yarn workspace @acala-network/eth-rpc-adapter run stop:coverage

      - name: save coverage reports
        uses: actions/upload-artifact@v3
        with:
          name: coverage-${{ matrix.project }}
          path: packages/eth-rpc-adapter/coverage-${{ matrix.project }}
          if-no-files-found: error
          include-hidden-files: true

      - name: dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2

  merge-and-upload-coverage-reports:
    runs-on: ubuntu-latest
    needs: [pkg-tests, e2e-tests]
    strategy:
      matrix:
        pkg: [bodhi, eth-providers, eth-rpc-adapter, eth-transactions]
        e2e: [e2e-hardhat, e2e-truffle, e2e-viem]
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: setup yarn
        run: npm install -g yarn

      - name: install deps
        run: yarn install --immutable

      - name: download package coverage reports
        uses: actions/download-artifact@v3
        with:
          name: coverage-${{ matrix.pkg }}
          path: packages/${{ matrix.pkg }}/coverage

      - name: Download e2e coverage reports
        uses: actions/download-artifact@v3
        with:
          name: coverage-${{ matrix.e2e }}
          path: packages/eth-rpc-adapter/coverage-${{ matrix.e2e }}

      - name: merge coverage reports
        run: yarn merge-coverage

      - name: upload merged coverage report
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
