name: Tests
on:
  push:
    paths-ignore:
      - '**/README.md'

jobs:
  cancel-prev-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        # Only cancel non-master branch runs
        if: ${{ github.ref != 'refs/heads/master' }}
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

  eth-providers:
    runs-on: self-hosted
    needs: cancel-prev-runs
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup yarn
        run: npm install -g yarn

      - name: setup node env
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - run: yarn install --immutable
      - run: yarn build:waffle

      - name: Build bodhi-runner
        run: docker build . -t bodhi-runner -f docker/bodhi-runner.Dockerfile

      - name: test
        run: docker compose up --abort-on-container-exit --exit-code-from=eth-providers-test --build -- eth-providers-test

      - name: dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2

  eth-rpc-adaptor:
    runs-on: self-hosted
    needs: cancel-prev-runs
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup yarn
        run: npm install -g yarn

      - name: setup node env
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - run: yarn install --immutable
      - run: yarn build:waffle

      - name: Build bodhi-runner
        run: docker build . -t bodhi-runner -f docker/bodhi-runner.Dockerfile

      - name: test
        run: docker compose up --abort-on-container-exit --exit-code-from=eth-rpc-adapter-test --build -- eth-rpc-adapter-test

      - name: dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2

  waffle-examples:
    runs-on: self-hosted
    needs: cancel-prev-runs
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup yarn
        run: npm install -g yarn

      - name: setup node env
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - run: yarn install --immutable
      - run: yarn build:waffle

      - name: Build bodhi-runner
        run: docker build . -t bodhi-runner -f docker/bodhi-runner.Dockerfile

      - name: test
        run: docker compose up --abort-on-container-exit --exit-code-from=waffle-examples-test --build -- waffle-examples-test

      - name: dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2

  hardhat-tutorials:
    runs-on: self-hosted
    needs: cancel-prev-runs
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup yarn
        run: npm install -g yarn

      - name: setup node env
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: install dependencies
        run: yarn install --immutable

      - name: Build bodhi-runner
        run: docker build . -t bodhi-runner -f docker/bodhi-runner.Dockerfile

      - name: test
        run: yarn e2e:hardhat

      - name: dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2

  truffle-tutorials:
    runs-on: self-hosted
    needs: cancel-prev-runs
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup yarn
        run: npm install -g yarn

      - name: setup node env
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: install dependencies
        run: yarn install --immutable

      - name: Build bodhi-runner
        run: docker build . -t bodhi-runner -f docker/bodhi-runner.Dockerfile

      - name: test
        run: yarn e2e:truffle

      - name: dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2

  tests:
    runs-on: ubuntu-latest
    needs: cancel-prev-runs
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: setup yarn cache
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: install dependencies
        run: yarn install --immutable

      - name: lint
        run: yarn lint

      - name: test
        run: yarn test

      - name: build
        run: yarn build

  e2e-tests:
    runs-on: self-hosted
    needs: cancel-prev-runs
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup yarn
        run: npm install -g yarn

      - name: setup yarn cache
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: install dependencies
        run: yarn install --immutable

      - name: build waffle tests
        run: yarn build:waffle

      - name: build bodhi-runner
        run: docker build . -t bodhi-runner -f docker/bodhi-runner.Dockerfile

      - name: e2e:eth-providers
        run: |
          yarn e2e:eth-providers
      - name: dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2

      - name: e2e:eth-rpc-adapter
        if: always()
        run: |
          docker compose down
          yarn e2e:eth-rpc-adapter
      - name: dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2


  tutorials-tests:
    runs-on: self-hosted
    needs: cancel-prev-runs
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup yarn
        run: npm install -g yarn

      - name: setup yarn cache
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: install dependencies
        run: yarn install --immutable

      - name: build waffle tests
        run: yarn build:waffle

      - name: build bodhi-runner
        run: docker build . -t bodhi-runner -f docker/bodhi-runner.Dockerfile

      - name: e2e:waffle
        shell: bash
        run: |
          yarn e2e:waffle

      - name: dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2

      - name: e2e:hardhat
        if: always()
        run: |
          docker compose down
          yarn e2e:hardhat

      - name: dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2

      - name: e2e:truffle
        if: always()
        run: |
          docker compose down
          yarn e2e:truffle

      - name: dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2

