name: Tests
on:
  push:
    paths-ignore:
      - '**/README.md'

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [
          eth-providers,
          eth-rpc-adapter,
          eth-transactions,
        ]
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: setup yarn
        run: npm install -g yarn

      - name: install deps
        run: yarn install --immutable

      - name: start test infra
        run: docker compose up -d

      - name: run tests
        run: yarn workspace @acala-network/${{ matrix.project }} run test:coverage

      - name: save coverage reports
        uses: actions/upload-artifact@v3
        with:
          name: coverage-${{ matrix.project }}
          path: packages/.coverage/${{ matrix.project }}

  e2e-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [
          e2e-hardhat,
          # e2e-truffle,
          # e2e-waffle,
          # e2e-viem,
        ]
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: setup yarn
        run: npm install -g yarn

      - name: install deps
        run: yarn install --immutable

      - name: start test infra
        run: docker compose up -d

      - name: run e2e tests
        env:
          COVERAGE_DIR: .coverage/${{ matrix.project }}
        run: yarn workspace @acala-network/eth-rpc-adapter run test:coverage

      - name: save coverage reports
        uses: actions/upload-artifact@v3
        with:
          name: coverage-${{ matrix.project }}
          path: packages/.coverage/${{ matrix.project }}

  merge-and-upload-coverage:
    runs-on: ubuntu-latest
    needs: [tests, e2e-tests]
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: setup yarn
        run: npm install -g yarn

      - name: install deps
        run: yarn install --immutable

      - name: download coverage reports for eth-providers
        uses: actions/download-artifact@v3
        with:
          name: coverage-eth-providers
          path: packages/.coverage/eth-providers

      - name: download coverage reports for eth-rpc-adapter
        uses: actions/download-artifact@v3
        with:
          name: coverage-eth-rpc-adapter
          path: packages/.coverage/eth-rpc-adapter

      - name: download coverage reports for eth-transactions
        uses: actions/download-artifact@v3
        with:
          name: coverage-eth-transactions
          path: packages/.coverage/eth-transactions

      - name: download coverage reports for e2e-hardhat
        uses: actions/download-artifact@v3
        with:
          name: coverage-e2e-hardhat
          path: packages/.coverage/e2e-hardhat

      - name: merge coverage reports
        run: yarn merge-coverage

      - name: upload merged coverage report
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
